services:
  - type: web
    name: cvd-risk-app
    env: docker
    repo: https://github.com/crabstertechnology/cvd-risk-app
    branch: master          # ‚Üê fix this line
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
